### ISSUE TITLE
Not working: not displaying preference on edit preference

### ISSUE THREAD

**Issue by allabur** [github-young/zotero-better-authors#77] opened 2024-10-01 09:28 UTC
Hello, 

The plugin is not working as expected. It is not showing the self-explanatory settings panel in Zotero 7 settings, nor the option to show columns of the last author or anything.

Windows 11 x64
Zotero 7.0.5 (64-bit)

Error console
![image](https://github.com/user-attachments/assets/1b23256d-61b6-4b6f-aec6-b408a9f65234)

**Comment by github-young** [comment] 2024-10-01 10:34
Have you tried disabling all other plugins and see if this issue can be stably reproduced?

**Comment by allabur** [comment] 2024-10-01 10:50
> Have you tried disabling all other plugins and see if this issue can be stably reproduced?

Yes, still not working...

**Comment by allabur** [comment] 2024-10-01 11:09
I have tried. It works. I identified at least one "incompatibility" with at least another plugin: https://github.com/windingwind/zotero-actions-tags#readme

**Comment by github-young** [comment] 2024-10-01 11:48
I am also using `zotero-actions-tags` and I cannot reproduce the same issue. The 3 plugins are all developed based on windingwind's template and they should be compatible.
Let's see if more users report similar issues.

**Comment by allabur** [comment] 2024-10-01 11:54
Zotero Better Authors 4.1.4 Last Updated September 29, 2024
& 
Actions and Tags for Zotero 2.0.2 Last Updated September 27, 2024

**Comment by github-young** [comment] 2024-10-01 12:00
For the error msg in your screenshot, `this.globalCache is undefined`, from the search results, I highly doubt it may be caused by the `zotero-better-notes` plugin as this repo is the only one that gives something related to `this.globalCache is undefined` in the GitHub discussion channel, such as 
https://github.com/windingwind/zotero-better-notes/discussions/521
https://github.com/windingwind/zotero-better-notes/discussions/903
But I am not quite sure if it is the real reason.

**Comment by daeh** [comment] 2024-10-02 18:10
There seem to be related issues in 
https://github.com/Dominic-DallOsto/zotero-reading-list/issues/58
https://github.com/daeh/zotero-markdb-connect/issues/138

**Comment by github-young** [comment] 2024-10-02 18:24
I will be able to look into the details after mid Nov, hope there will be other developers working on it (probably due some changes in upstream)

**Comment by zhanghm1995** [comment] 2024-10-14 12:15
Also encounter this problem, every time I need to uninstall all plug-ins, and then one by one to install back on it.

![image](https://github.com/user-attachments/assets/10994433-d1a6-4c31-90a8-ff15bf6ef90f)

**Comment by github-young** [comment] 2024-10-15 13:57
@allabur @ChrisMFChung @zhanghm1995 
Could you please try this quick fix to see if this error happens again?

To be noted that this one is a very preliminary fix and it comes with other problems, such as the preference does not affect the displayed results. I just want to check if this `TypeError: globalCache is undefined` message shows again. We will investigate it with more time in the future Thank you.

[zotero-better-test.zip](https://github.com/user-attachments/files/17379247/zotero-better-test.zip)

**Comment by github-young** [comment] 2024-10-16 04:01
Fixed in https://github.com/github-young/zotero-better-authors/releases/tag/v4.2.0

**Closed by github-young** 2024-10-16 04:01 UTC
